var require = {
  baseUrl: '../',
  paths: {
    'main': 'ChromeExtension/js/foreground/main',
    'playerstates': 'ChromeExtension/js/playerstates',
    'foreground':'ChromeExtension/js/foreground/foreground',
    'uielements': 'ChromeExtension/js/foreground/uielements',
    'player_controls': 'ChromeExtension/js/foreground/player_controls/player_controls',
    'volume_slider': 'ChromeExtension/js/foreground/player_controls/volume_slider',
    'playpause_button': 'ChromeExtension/js/foreground/player_controls/playpause_button',
    'skip_button': 'ChromeExtension/js/foreground/player_controls/skip_button',
    'previous_button': 'ChromeExtension/js/foreground/player_controls/previous_button',
    'shuffle_button': 'ChromeExtension/js/foreground/player_controls/shuffle_button',
    'header': 'ChromeExtension/js/foreground/header',
    'settings': 'ChromeExtension/js/foreground/settings_tab/settings',
    'songs_tab': 'ChromeExtension/js/foreground/songs_tab/songs_tab',
    'songlist_context_menu': 'ChromeExtension/js/foreground/songs_tab/songlist_context_menu',
    'songlist': 'ChromeExtension/js/foreground/songs_tab/songlist',
    'songinput': 'ChromeExtension/js/foreground/songs_tab/songinput',
    'playlists_tab': 'ChromeExtension/js/foreground/playlists_tab/playlists_tab',
    'playlist_list': 'ChromeExtension/js/foreground/playlists_tab/playlist_list',
    'playlists_context_menu': 'ChromeExtension/js/foreground/playlists_tab/playlists_context_menu',
    'context_menu': 'ChromeExtension/js/foreground/context_menu',
    'content_header': 'ChromeExtension/js/foreground/content_header',
    'time_display': 'ChromeExtension/js/foreground/time_display',
    'dialogs': 'ChromeExtension/js/foreground/dialogs',
    'content_buttons': 'ChromeExtension/js/foreground/content_buttons',
    'progress_bar': 'ChromeExtension/js/foreground/progress_bar',
    'youtube-player-api-helper': 'Shared/js/third_party/youtube-player-api-helper',
    'onYouTubePlayerAPIReady': 'Shared/js/third_party/onYouTubePlayerAPIReady',
    'jquery-mousewheel': 'Shared/js/third_party/jquery.mousewheel',
    'song_builder': 'Shared/js/song_builder',
    'yt_helper': 'Shared/js/yt_helper',
    'helpers': 'Shared/js/helpers',
    'jquery': 'Shared/js/third_party/jquery-1.7.2',
    'jquery-ui': 'Shared/js/third_party/jquery-ui-1.8.21.custom.min',
    'geoplugin': 'Shared/js/third_party/geoplugin',
    'levenshtein': 'Shared/js/third_party/levenshtein',
    'underscore': 'Shared/js/third_party/underscore.min',
    'fblogin': 'Shared/js/fblogin'
  }
};