var require = {
  baseUrl: '../',
  paths: {
    'main': '/Website/scripts/main',
    'recognition': '/Website/scripts/recognition',
    'audioScrobbler': '/Shared/js/audioScrobbler',
    'backend': '/Website/scripts/backend',
    'fblogin': '/Shared/js/fblogin',
    'recognitionArea': '/Website/scripts/recognitionArea',
    'recognitionImageBuilder': '/Website/scripts/recognitionImageBuilder',
    'recognitionList': '/Website/scripts/recognitionList',
    'strings': '/Website/scripts/strings',
    'jquery': '/Shared/js/thirdParty/jquery',
    'geoplugin': '/Shared/js/thirdParty/geoplugin',
    'levenshtein': '/Shared/js/thirdParty/levenshtein',
    'songBuilder': '/Shared/js/songBuilder',
    'ytHelper': '/Shared/js/ytHelper',
    'helpers': '/Shared/js/helpers',
    'libraryController': '/Website/scripts/libraryController',
    'bindings': '/Website/scripts/bindings',
    'albums': '/Website/scripts/albums',
    'contextmaster': '/Website/scripts/contextmaster',
    'underscore': '/Shared/js/thirdParty/underscore',
    'songDecorator': '/Website/scripts/songDecorator',
    'supportedFormats': '/Shared/js/supportedFormats',
    'playerBuilder': '/Shared/js/playerBuilder',
    'player': '/Website/scripts/player',
    'ytPlayerApiHelper': '/Shared/js/thirdParty/ytPlayerApiHelper',
    'onYouTubePlayerApiReady': '/Shared/js/thirdParty/onYouTubePlayerApiReady',
    'playlists': '/Website/scripts/playlists',
    'navigation': '/Website/scripts/navigation',
    'search': '/Website/scripts/search',
    'artists': '/Website/scripts/artists',
    'jquerySlider': '/Shared/js/thirdParty/jquerySlider',
    'notifications': '/Website/scripts/notifications'
  },
  urlArgs: "bust=" + (new Date()).getTime()
};